[workspace]
members = [
    "rowifi",
    "cache",
    "database",
    "framework",
    "framework/framework-derive",
    "models",
    "redis",
    "roblox"
]

[profile.release]
lto = true