[package]
name = "rowifi-models"
version = "1.0.0"
authors = ["Gautam.A <gautam.abhyankar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "1"
itertools = "0"
prometheus = "0"
serde = "1"
serde_repr = "0"
twilight-http = { version = "0.2" }
twilight-model = { version = "0.2" }